# AWS CodeBuild config
# This file is referenced in the infra repo as a CodeBuild buildspec target.

# These variables are set in the codebuild project definition's environment secion.
# ECR_*

version: 0.2
env:
  shell: bash

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region "${ECR_REGION}" | docker login --username AWS --password-stdin "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com"

  build:
    commands:
      - export ECR_HOST="${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com"
      - export ECR_REPO="${ECR_HOST}/${ECR_NAMESPACE}"

      - docker build .  -t "${ECR_REPO}/dw-outofservice:run-candidate"

      # Push migration image(s)

      - docker push "${ECR_REPO}/dw-outofservice:run-candidate"
